---
- name: configure nginx repo
  include: repos.yml
  when: nginx_upstream_repo

- name: install nginx
  yum: name=nginx state=present
  tags:
    - nginx
    - packages

- name: configure nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: restart nginx
  tags:
    - nginx
    - configuration

- name: ensure nginx is enabled and running
  service: name=nginx enabled=yes state=started
  tags:
    - nginx
    - configuration
    - services