---
- name: install nginx repo key
  rpm_key: key=http://nginx.org/packages/keys/nginx_signing.key state=present
  tags:
    - nginx
    - repos
    - packages

- name: install nginx repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644
  tags:
    - nginx
    - repos
    - packages
